### PR TITLE
Fix translation

### PR DESCRIPTION
**Pull request by mattreim**
Pin-translation

### CODE REVIEW

**Comment by mcm1957** [comment]
This adapter uses WEBLATE  for translations.
Please avoid changing translations directly but edit at weblate as this might cause merge conflicts

see https://github.com/ioBrokerTranslator/doc

**Comment by mcm1957** [comment]
Still the question is open what this PR is good for.
Why do ypu change so many test ?

Changes should be perfomed at WEBLATE only.
And existing Text should be changes only if it is incorrect. I doubt that you checked russian and chinese text?

I would suggest to close the PR and to correct entually incorrect test at weblate. Thats the desired way

**Comment by mattreim** [comment]
In this case, WEBLATE translated at least 3 of 11 words correctly. So something really seems wrong there.

**Comment by mcm1957** [comment]
weblate does nothing translate itself. Its a tool to manually translate. See documentation.

**Comment by mattreim** [comment]
The green ones were taken over and the red ones were not. You can see it in the second screenshot above.

**Comment by mattreim** [comment]
The translation will not be accepted.

**Comment by mattreim** [comment]
The adapter does not use the i18n file

**Comment by mattreim** [comment]
That's why I also had to add the package.json.

**Comment by mcm1957** [comment]
Also ich sehe in den i18n Dateine diese Texte:
image

**Comment by mattreim** [comment]
And the words crossed out in red are no longer used.

**Comment by mattreim** [comment]
Therefore, I rearranged and recreated the translation.

**Comment by mcm1957** [comment]
> And the words crossed out in red are no longer used.

Please check the code too if this text is no longer used. I know adapter who use the i18n text within code too. So if you did not remove the source personally be very carefull before removing anything.

> Therefore, I rearranged and recreated the translation.

If the unused text should really be removed it should be enough to remove it from master file (englisch file) Weblate should do the rest. Its not desired to rerun automatic translation as this most likely desturbes already manually corrected text.

**Comment by mattreim** [comment]
OK, I will make a new PR and keep old text. Thank you for your patience.

**Comment by mattreim** [comment]
>If the unused text should really be removed it should be enough to remove it from master file (englisch file) Weblate should do the rest. Its not desired to rerun automatic translation as this most likely desturbes already manually corrected text.

Good to know, I'll stick to it.

**Comment by mcm1957** [comment]
Ok
Thanks very much  for your Support

**Pull request closed without merging**
