### PR TITLE
Revert license to io-package [fix AssertionError]

### PR DESCRIPTION
**Pull request by mattreim**

### CODE REVIEW

**Comment by mcm1957** [comment]
Please use licenseInformation.
License attribute is deprecated88

**Comment by mattreim** [comment]
Ping-Error

But test-and-release has a problem with it and this makes it work.

**Comment by mattreim** [comment]
The last versions (1.6.3 and 1.6.4) were not released either.

**Comment by mcm1957** [comment]
License ist still outdated. And licenseinformation is current.

Ifciobroker testing iis up to date this will work.

**Pull request closed without merging**
