### PR TITLE
changing host handing when "." is in in the channel name

### PR DESCRIPTION
**Pull request by Apollon77**
The reason for the failing tests on mac was a hostname with „.local“ at the end. Because of this the channel was created with a sub-structure.

Even when it is a „Breaking“ change my idea would be to handle that correctly and replace the „.“ to have a correct data structure …

What do you think?

### CODE REVIEW

**Comment by Apollon77** [comment]
ALternative would be to fix the object name tests in the test-logic and stay with the "sub-structured-keys" ...

**Comment by GermanBluefox** [comment]
On the one side, it is not bad to have structure in names of objects and name.local is not bad.
I think we can allow points in the names, but only if it is **not** IPv4 address. Because it creates too many groups.

**Comment by Apollon77** [comment]
But especially this structure is "the wrong order". A structure with "local -> hostname" makes sense because you have then all hosts that have a ".local" grouped together. 
Currently the order is "hostname -> local" ... so the local is just another level in the structure which is unneeded.

But because of backward compatibility I will change it back and change the testing logic

**Comment by Apollon77** [comment]
So change reverted and found a way to set an hostname without ".local" for macos tests :-)

**Pull request merged**
