### PR TITLE
Fixed arguments

### PR DESCRIPTION
**Pull request by misterx**
Fixed stderr error message `ping: invalid number ' 2'` that raise wrong result described in #12

### CODE REVIEW

**Comment by Apollon77** [comment]
Linux Tests are failing ...

**Comment by misterx** [comment]
Hm ... so strange ... this fix working fine for me. Original code caused an error as in CI before my changes. I've used Node 8.12 and npm 6.4.1.

**Comment by misterx** [comment]
```
2018-11-09 16:29:46.736  - debug: ping.0 System command: /bin/ping -n -w  2 -c  1 192.168.168.168
2018-11-09 16:29:46.740  - debug: ping.0 STDERR: ping: bad number of packets to transmit.
```

I think problem in arguments escaping on different platforms. I'm using docker mhart/alpine-node:8

**Comment by misterx** [comment]
As in docs examples https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options 
Command `ls -lh /usr` is represented as two elements in arguments `spawn('ls', ['-lh', '/usr'])` not one as  `spawn('ls', ['-lh /usr'])`

**Comment by Apollon77** [comment]
i removed the spaces after the commands in the strings ... maybe this helps

**Comment by misterx** [comment]
Looks like this helped

**Comment by Apollon77** [comment]
Yes put it in my todo list. Or do it and sent an other pr ;-) package and io-package needs to be updated

**Pull request merged**
