### PR TITLE
refactored, added ping time and roundtrips per second for every host

### PR DESCRIPTION
**Pull request by vdemidov**
Mach changes. Adapter create channel with several states for every host. Now three states exist: 
alive -- boolean, indicator.reachable -- is host reachable
time -- number, value.interval -- time of ping in seconds
rps -- number, value -- number of round trips to host per second

### CODE REVIEW

**Comment by Apollon77** [comment]
Are the changes backward compatible? I saw that you changed the tests to the ".alive" state instead of the "IP-only" state. many scripts may subscribe to the states where currently the availability can be found, so move it will break these skripts.
You can also set a value for a "channel" vis "setState". When you do that additionally to the ".alive" it is backward compatible. Can you please look into it?

Additionally when you also increase the version in package.json, io-package.json and add changelog in README it will be faster to release the changes :-)

**Comment by vdemidov** [comment]
> You can also set a value for a "channel" vis "setState". When you do that additionally to the ".alive" it is backward compatible. 
Are you sure? It's simple to add. But I'm not sure that this is correct.

**Comment by Apollon77** [comment]
I think so ( i have other adapters where also channels habe a value of true/false or such :-)
Try it. to verify simply change the tests where you set to ".alive" and duplicate the line to check both locations for the value. Tests should then tell you

**Comment by vdemidov** [comment]
Done.

**Comment by Apollon77** [comment]
You closed why?!

I do not had time to deeply check it

**Comment by Apollon77** [comment]
cool. thank you!

**Pull request closed without merging**
